### ISSUE TITLE
Video not playing back

### ISSUE THREAD

**Issue by blindpet** [sebas7dk/popstop#1]
Referencing the reddit post https://www.reddit.com/r/raspberry_pi/comments/3swo9f/stream_your_movies_from_your_raspberry_pi_to_your/cx1b0q5

The mime types was cut off so I may be missing some important ones, can you format it with line breaks?

I did add the ones I could see, restart nginx and deleted the sqlite db and re-configured. Still no video showing.

**Comment by sebas7dk** [comment]
Here are the mime types you should add. 

```
        video/3gpp                              3gpp 3gp;
        video/mp4                               mp4;
        video/mpeg                              mpeg mpg mpe;
        video/ogg                               ogv;
        video/quicktime                         mov;
        video/webm                              mkv;
        video/x-flv                             flv;
        video/x-mng                             mng;
        video/x-ms-asf                          asx asf;
        video/x-ms-wmv                          wmv;
        video/x-msvideo                         avi;
```

But do you actuall have any files indexed and showing up with information?

**Comment by blindpet** [comment]
Those are there by default and the include /etc/nginx/mime.types in /etc/nginx/nginx.conf is uncommented

3 files are showing up with information and I can click Play, just get infinite loading when I do.

**Comment by sebas7dk** [comment]
Hmm the infinite loading means it can't play or find the file. What is your console output? Are you using Google Chrome?

**Comment by blindpet** [comment]
```
Failed to load resource: the server responded with a status of 400 (Bad Request)
popstop.min.js:1 Uncaught TypeError: Cannot read property 'length' of undefined
ncaught IndexSizeError: Failed to execute 'end' on 'TimeRanges': The index provided (0) is greater than or equal to the maximum bound (0).
```

Yes I am using Chrome, I have tried Firefox too

**Comment by sebas7dk** [comment]
Can you change the index.html file and replace the file:

```
<script type="text/javascript" src="/app/public/js/scripts/popstop.min.js"></script>
```

with:

```
<script type="text/javascript" src="/app/public/js/src/popstop.js"></script>
```

**Comment by blindpet** [comment]
Done, still getting the loop and this error in Console line 403

```
Uncaught TypeError: Cannot read property 'length' of undefined in popstop.js
```

When I stop the video I get this error in player.min.js line 1

```
ncaught IndexSizeError: Failed to execute 'end' on 'TimeRanges': The index provided (0) is greater than or equal to the maximum bound (0).
```

And when I switch videos after pausing this error  in jquery-2.1.4 in line 3

```
GET http://image.tmdb.org/t/p/w1280 400 (Bad Request)
```

**Comment by sebas7dk** [comment]
Does it say what line? Also does nginx have access to the content directory?

**Comment by blindpet** [comment]
Chrome doesn't look to include lines, updated previous post to include lines

**Comment by sebas7dk** [comment]
Can you click on the settings icon and do a Re-install it looks like it hasn't fetched all the information from TMDB.

**Comment by sebas7dk** [comment]
Can you put this file in the content directory and see if it works? http://demo.popstop.io/content/Fight%20Club.mp4

**Comment by blindpet** [comment]
OK that video worked, that is strange since the Big buck bunny video I linked to plays in Chrome too so is there a limited amount of codecs this supports?

**Comment by sebas7dk** [comment]
Hmm that's funny because the big buck bunny video is used everywhere to play with html5. I have tried it with avi, mp4, mkv files and didnt have any issues. I know it won't play anything other than the AAC audio format. But I will look into this video why it is not playing. Can I close the issue.

**Comment by blindpet** [comment]
Maybe more mime types need to be added for different codecs? Closing but do update this issue when you've tested so I can verify.

For example the videos I am testing require no transcoding in Plex for the Plex Web Player

**Comment by sebas7dk** [comment]
What I can see is that the file uses the ac3 audio format and chrome doesn't support ac3 audio formats, only aac.
