### ISSUE TITLE
Error without an error message

### ISSUE THREAD

**Issue by sidc9** [sebas7dk/popstop#2]
Hi, I am getting an error without any kind of message displayed. 
<img width="836" alt="capture" src="https://cloud.githubusercontent.com/assets/13518498/11216944/ea5da38a-8d88-11e5-9807-495838c22104.PNG">

Could you please help?  Before this I got the message Curl extension not loaded. So I reinstalled Curl, and modified the php.ini according to info I found on Stackoverflow. After that, visiting my Pi's IP gives this error page.

**Comment by sebas7dk** [comment]
Hi, 
What is the console output and is app/database writable, also did you reload php-fpm after installing curl?

**Comment by sidc9** [comment]
Could you tell me how to see console output? 

I changed file permissions for app/database  to 777.

I did reload php-fpm, as well as reboot the Pi multiple times.

Also, before Curl was installed, I at least got the first 1 or 2 setup pages and it went as far as the API key. The Curl not installed message was shown after that.

Now, however, the image I previously attached is the only thing which shows up when I visit the Pi's IP.

**Comment by sebas7dk** [comment]
Can you remove the popstop.sqlite file in app/database and restart the installation process. To see the console output in google chrome you just have right click on the webpage and click on inspect element and then click on the console tab.

**Comment by sidc9** [comment]
I removed the sqlite file, checked permissions of app/database and refreshed the page. Still no luck.

Console output:

<img width="419" alt="capture" src="https://cloud.githubusercontent.com/assets/13518498/11272670/90758dec-8f09-11e5-8b7b-35aa6a507048.PNG">

PS: Thanks for your prompt replies! It's really appreciated.

**Comment by sebas7dk** [comment]
What do you get when you go to 192.168.0.121/bootstrap.php?function=isInstalled? It looks like it's not loading php. are you using nginx or apache?

**Comment by sidc9** [comment]
I'm using Nginx. (I already have a small webpage running successfully,
which I have removed from the www/ folder to install Popstop.)

And  I just get Server Error 500 if I try to go to either,
- 192.168.0.121/bootstrap.php, or
- 192.168.0.121/bootstrap.php?function=isInstalled

Siddhanta Chakrabarty

On Thu, Nov 19, 2015 at 10:29 PM, Sebastian de Kok <notifications@github.com

**Comment by sebas7dk** [comment]
Can you move the files to a folder called popstop and point nginx to that folder? What does your nginx config look like?

**Comment by sidc9** [comment]
Did that. Still the same error message.
I've attached whole the config. I've also attached a screenshot of what I think is the main portion.
<img width="436" alt="capture" src="https://cloud.githubusercontent.com/assets/13518498/11275929/ccc84468-8f1a-11e5-813a-62b5cf32a741.PNG">

[nginx_config.txt](https://github.com/sebas7dk/popstop/files/39146/default.txt)

**Comment by sebas7dk** [comment]
Change it to something like this, it's also common to put your web content in /var/www instead of usr/share/nginx.

``` txt
server { 
   listen 80; server_name popstop.io; 
   root "/var/www/html/popstop";
   index index.html index.htm index.php .index.php;
   error_log  /var/log/nginx/popstop-error.log error;

 location / {
     try_files $uri $uri/ =404;
 }

 location ~ \.php$ {
      try_files $uri =404;
      fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
      fastcgi_index index.php;
      fastcgi_param SCRIPT_FILENAME   $document_root$fastcgi_script_name;
      include fastcgi_params;
  }
} 
```

**Comment by sidc9** [comment]
Made all the changes. Still the same error in the browser as well as console. 

The strange part is, the first time it at least went as far as the API key and then failed. Now nothing works at all.

**Comment by sidc9** [comment]
I also found this in nginx's error.log

2015/11/20 01:06:15 [error] 2676#0: *37 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'PDO' not found in /usr/share/nginx/popstop/app/src/Classes/DBlite.php on line 33" while reading response header from upstream, client: 192.168.0.113, server: localhost, request: "GET /bootstrap.php?function=isInstalled HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "192.168.0.121", referrer: "http://192.168.0.121/"

**Comment by sebas7dk** [comment]
Aah okay that explains a lot, did you install php5-sqlite?

**Comment by sidc9** [comment]
I believe so.

On running 

`$ dpkg -s php5-sqlite`

I get this output

```
Package: php5-sqlite
Status: install ok installed
Priority: optional
Section: php
Installed-Size: 59
Maintainer: Debian PHP Maintainers <pkg-php-maint@lists.alioth.debian.org>
Architecture: armhf
Source: php5
Version: 5.4.45-0+deb7u2
Depends: libc6 (>= 2.13-28), libsqlite3-0 (>= 3.7.4), phpapi-20100525+lfs, php5-common (= 5.4.45-0+deb7u2), ucf
Pre-Depends: dpkg (>= 1.16.1~)
Breaks: roundcube-sqlite (<< 0.7.1-2)
Description: SQLite module for php5
 This package provides a module allowing you to use the SQLite self-contained
 database engine from within your PHP scripts, eliminating the need for a full
 SQL server installation like MySQL or PostgreSQL.  It also includes the
 pdo_sqlite module, for use with the PHP Data Object extension.
 .
 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used
 open source general-purpose scripting language that is especially suited
 for web development and can be embedded into HTML.
Homepage: http://www.php.net/
```

Do I have to activate or run it or something like that?

**Comment by sidc9** [comment]
Sorry, clicked the 'Close and Comment' button by mistake.

**Comment by sebas7dk** [comment]
Can you run sudo apt-get install php5-mysql and that should fix it as you don't have the pdo module installed.

**Comment by sidc9** [comment]
Unfortunately, that didn't help either. 

I tried to run sudo apt-get isntall php5-pdo too but it didn't work.

From the phpinfo(),

Additional ini files parsed:

```
/etc/php5/fpm/conf.d/10-pdo.ini, 
/etc/php5/fpm/conf.d/20-mysql.ini, 
/etc/php5/fpm/conf.d/20-mysqli.ini, 
/etc/php5/fpm/conf.d/20-pdo_mysql.ini, 
/etc/php5/fpm/conf.d/20-pdo_sqlite.ini, 
/etc/php5/fpm/conf.d/20-sqlite3.ini
```

**Comment by sebas7dk** [comment]
Can you create a php file inside your web root with phpinfo () in it and then open that page and send me a screenshot of the output.

**Comment by sidc9** [comment]
Screenshot

<img width="470" alt="capture" src="https://cloud.githubusercontent.com/assets/13518498/11318155/45dadd2c-9081-11e5-8ef4-3cd6f2b9d9f2.PNG">

The whole file 
[phpinfo().txt](https://github.com/sebas7dk/popstop/files/40792/phpinfo.txt)
(Rename it to phpinfo().html and it should open)

**Comment by sebas7dk** [comment]
hmm can you run php -m on your raspberry pi and check if the module PDO is in the list?

**Comment by sidc9** [comment]
I got "bash: command not found" for 'php'.

So after some looking around online I  installed php5-cgi, php5 and finally php-cli. After installing the last one, the 'php' command started working and PDO is in the list after doing php -m. 

Do you think my php installation is somehow screwed up? Will it help if I reinstall PHP? But even if I do, I don't see how it will change anything because the only changes I had made to PHP before Popstop was to make it work with Nginx.

**Comment by sebas7dk** [comment]
You didn't have all the php modules installed, no need to re-install php. Can we close this ticket or do you need more help?

**Comment by sidc9** [comment]
Well it's still not working. But I don't see what else can be done. You've been most helpful, thank you. 

If you don't have any other suggestions, I guess it can be closed.

**Comment by sebas7dk** [comment]
Ow sorry I understood it was working, yes please do a fresh install of php with all the modules.

``` txt
sudo apt-get -y install php5-common php5-cgi php5 php5-sqlite php5-curl
```

**Comment by sidc9** [comment]
Okay, thanks. I'll try that tomorrow.

**Comment by sebas7dk** [comment]
You should download the latest release, it has a fix to make it work with apache. If you don't get it to work  with the latest version please raise a new ticket.

**Comment by sidc9** [comment]
I haven't had time to reinstall PHP yet. I'll try that, along with the new version and get back to you with the results. 

Thanks for the wonderful support.

**Comment by sidc9** [comment]
Hey, thanks a lot. It's working now! Didn't require Apache, Nginx was enough. However, it can't process any of the files, so I'll raise a new ticket for that.
