### ISSUE TITLE
Unable to process/parse movie files

### ISSUE THREAD

**Issue by sidc9** [sebas7dk/popstop#3]
Thanks for your support with my earlier issue. Now that it's working, it can't seem to process any of the movies. This is what file and folder titles look like:

![capture](https://cloud.githubusercontent.com/assets/13518498/11401627/72e90c08-93ce-11e5-9cd0-9d6cb7494674.PNG)

As you can see, the years are included in the title. 

This was the error message:

![capture](https://cloud.githubusercontent.com/assets/13518498/11401700/c9c129b6-93ce-11e5-8835-e21ee56171d2.PNG)

**Comment by sebas7dk** [comment]
Remove all the unnecessary information like 1080p and so on, just the title and the year is enough.
